# Generated by Django 5.0.4 on 2024-10-28 11:09

import home.models
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='black_logo',
            new_name='icon_black_logo',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='white_logo',
            new_name='icon_white_logo',
        ),
        migrations.AddField(
            model_name='setting',
            name='name_black_logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=home.models.logo_image_path),
        ),
        migrations.AddField(
            model_name='setting',
            name='name_white_logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=home.models.logo_image_path),
        ),
        migrations.AddField(
            model_name='setting',
            name='second_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
