# Generated by Django 5.0.4 on 2024-10-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='github',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
