# Generated by Django 5.0.4 on 2024-10-29 07:33

import home.models
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_team_github_team_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=home.models.portfolio_image_path)),
                ('big_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=home.models.portfolio_image_path)),
                ('category', models.CharField(blank=True, choices=[('Web App', 'Web App'), ('Logo', 'Logo'), ('UI/UX', 'UI/UX'), ('Mobile App', 'Mobile App')], max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='portfolios', to='home.tag')),
            ],
            options={
                'verbose_name_plural': 'Portfolios',
            },
        ),
    ]
