# Generated by Django 5.0.4 on 2024-10-29 07:35

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_tag_portfolio'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
