# Generated by Django 5.0.4 on 2024-10-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_tag_alter_portfolio_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='tags',
        ),
    ]
