# Generated by Django 5.0.4 on 2024-10-29 07:38

import home.models
import imagekit.models.fields
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_portfolio_tags'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, choices=[('Web App', 'Web App'), ('Logo', 'Logo'), ('UI/UX', 'UI/UX'), ('Mobile App', 'Mobile App')], max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
