# Generated by Django 5.0.4 on 2024-10-29 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_portfolio_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
