# Generated by Django 5.0.4 on 2024-10-29 07:49

import home.models
import imagekit.models.fields
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_portfolio'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=home.models.portfolio_image_path)),
                ('big_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=home.models.portfolio_image_path)),
                ('category', models.CharField(blank=True, choices=[('Web App', 'Web App'), ('Logo', 'Logo'), ('UI/UX', 'UI/UX'), ('Mobile App', 'Mobile App')], max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Portfolios',
            },
        ),
    ]
