# Generated by Django 5.0.4 on 2025-02-16 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='client_phone_number',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='home.client'),
        ),
    ]
