# Generated by Django 5.0.4 on 2025-02-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_portfolio_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='figma_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_category',
            field=models.CharField(blank=True, choices=[('Student Project', 'Student Project'), ('Client Project', 'Client Project'), ('Learning Project', 'Learning Project')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='repo_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='system_analysis_document',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/system_analysis/'),
        ),
    ]
