# Generated by Django 5.0.4 on 2025-02-16 15:53

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_testimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image_png',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.team_png_image_path),
        ),
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
