# Generated by Django 5.0.4 on 2025-03-05 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_team_image_png_team_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimony',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to='home.client'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='message',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
