# Generated by Django 5.0.4 on 2025-03-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_team_slug_alter_testimony_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
