# Generated by Django 5.0.4 on 2025-08-04 22:07

import django.db.models.deletion
import home.models
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='big_image',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=home.models.portfolio_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Image',
                'verbose_name_plural': 'Portfolio Images',
            },
        ),
    ]
