# Generated by Django 5.2.8 on 2025-11-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    """Historical state only.

    This migration originally used CKEditor's RichTextUploadingField.
    CKEditor has since been removed, so the field is declared as the
    TextField it always was in the database. The column type is
    identical, so no environment's schema changes, and the Portfolio
    model this touched was rebuilt from scratch in 0033.
    """

    dependencies = [
        ('home', '0028_remove_portfolio_big_image_remove_portfolio_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
