# Generated by Django 6.0.1 on 2026-09-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_portfolio_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='client',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='client',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='paymentstatus',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='team_members',
        ),
        migrations.RemoveField(
            model_name='portfoliorepo',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='portfolioimage',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Testimony',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentStatus',
        ),
        migrations.DeleteModel(
            name='PortfolioRepo',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioImage',
        ),
    ]
