# Generated by Django 6.0.1 on 2026-09-22 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_contact_and_setting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
    ]
