# Generated by Django 6.0.1 on 2026-09-23 14:25

import django.db.models.deletion
import home.storages
import home.upload_paths
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_team_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('web_application', 'Web Application'), ('mobile_application', 'Mobile Application'), ('ui_ux', 'UI/UX'), ('branding', 'Branding')], max_length=50)),
                ('project_type', models.CharField(choices=[('client_project', 'Client Project'), ('student_project', 'Student Project'), ('learning_project', 'Learning Project')], max_length=50)),
                ('live_url', models.URLField(blank=True, max_length=500)),
                ('figma_url', models.URLField(blank=True, max_length=500)),
                ('project_initiation_date', models.DateField(blank=True, null=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_members', models.ManyToManyField(blank=True, related_name='portfolios', to='home.team')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='PortfolioDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('system_analysis', 'System Analysis'), ('other', 'Other')], default='other', max_length=50)),
                ('file', models.FileField(storage=home.storages.raw_media_storage, upload_to=home.upload_paths.portfolio_document_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='home.portfolio')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=home.upload_paths.portfolio_gallery_image_path)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_cover', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.portfolio')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PortfolioRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Repository', max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='home.portfolio')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.CheckConstraint(condition=models.Q(('project_initiation_date__isnull', True), ('deadline_date__isnull', True), ('deadline_date__gte', models.F('project_initiation_date')), _connector='OR'), name='portfolio_deadline_on_or_after_start'),
        ),
        migrations.AddConstraint(
            model_name='portfolioimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('portfolio',), name='unique_portfolio_cover_image'),
        ),
        migrations.AddConstraint(
            model_name='portfoliorepository',
            constraint=models.UniqueConstraint(fields=('portfolio', 'url'), name='unique_portfolio_repository_url'),
        ),
    ]
