# Generated by Django 6.0.1 on 2026-09-23 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_portfolio_portfoliodocument_portfolioimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliodocument',
            options={'ordering': ('pk',)},
        ),
        migrations.RemoveField(
            model_name='portfoliodocument',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='portfoliodocument',
            name='file',
        ),
        migrations.AddField(
            model_name='portfoliodocument',
            name='url',
            field=models.URLField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='portfoliodocument',
            constraint=models.UniqueConstraint(fields=('portfolio', 'url'), name='unique_portfolio_document_url'),
        ),
    ]
