# Generated by Django 6.0.1 on 2026-09-23 19:37

import home.upload_paths
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_portfoliodocument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('profile_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=home.upload_paths.client_profile_image_path)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('active', 'inactive', 'archived'))), name='client_valid_status')],
            },
        ),
    ]
