# Generated by Django 6.0.1 on 2026-09-23 21:14

import home.upload_paths
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image_png',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=home.upload_paths.team_png_image_path),
        ),
    ]
