# Generated by Django 6.0.1 on 2026-09-24 14:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_contact_sender_details_and_replies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('agreement_type', models.CharField(choices=[('project', 'Project'), ('maintenance', 'Maintenance'), ('custom', 'Custom')], db_index=True, default='project', max_length=20)),
                ('currency', models.CharField(choices=[('RWF', 'Rwandan Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='RWF', max_length=3)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('agreement_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_agreements', to='home.portfolio')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('installment_type', models.CharField(choices=[('down_payment', 'Down Payment'), ('installment', 'Installment'), ('final_payment', 'Final Payment'), ('milestone', 'Milestone'), ('maintenance', 'Maintenance'), ('custom', 'Custom')], db_index=True, default='installment', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('due_type', models.CharField(choices=[('fixed_date', 'Fixed Date'), ('milestone', 'Milestone')], default='fixed_date', max_length=20)),
                ('expected_due_date', models.DateField(db_index=True)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('milestone', models.CharField(blank=True, max_length=255)),
                ('grace_period_days', models.PositiveSmallIntegerField(default=0)),
                ('is_waived', models.BooleanField(db_index=True, default=False)),
                ('waived_at', models.DateTimeField(blank=True, null=True)),
                ('waiver_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='home.paymentagreement')),
            ],
            options={
                'ordering': ('agreement_id', 'sequence', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(choices=[('RWF', 'Rwandan Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='RWF', max_length=3)),
                ('paid_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash'), ('card', 'Card'), ('cheque', 'Cheque'), ('other', 'Other')], default='bank_transfer', max_length=30)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('voided', 'Voided')], db_index=True, default='posted', max_length=20)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='home.paymentagreement')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-paid_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='home.paymentinstallment')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='home.paymentrecord')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='paymentagreement',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='payment_agreement_positive_total'),
        ),
        migrations.AddConstraint(
            model_name='paymentagreement',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='payment_agreement_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='paymentagreement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agreement_type', 'maintenance'), _negated=True), ('end_date__isnull', False), _connector='OR'), name='payment_agreement_maintenance_has_end'),
        ),
        migrations.AddConstraint(
            model_name='paymentagreement',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'active', 'completed', 'cancelled'))), name='payment_agreement_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='paymentagreement',
            constraint=models.CheckConstraint(condition=models.Q(('agreement_type__in', ('project', 'maintenance', 'custom'))), name='payment_agreement_valid_type'),
        ),
        migrations.AddConstraint(
            model_name='paymentagreement',
            constraint=models.CheckConstraint(condition=models.Q(('currency__in', ('RWF', 'USD', 'EUR', 'GBP'))), name='payment_agreement_valid_currency'),
        ),
        migrations.AddConstraint(
            model_name='paymentinstallment',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='payment_installment_positive_sequence'),
        ),
        migrations.AddConstraint(
            model_name='paymentinstallment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_installment_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='paymentinstallment',
            constraint=models.UniqueConstraint(fields=('agreement', 'sequence'), name='unique_payment_installment_sequence'),
        ),
        migrations.AddConstraint(
            model_name='paymentinstallment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('due_date__isnull', False), ('due_type', 'fixed_date'), ('milestone', '')), models.Q(('due_type', 'milestone'), models.Q(('milestone', ''), _negated=True)), _connector='OR'), name='payment_installment_valid_due_rule'),
        ),
        migrations.AddConstraint(
            model_name='paymentinstallment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_waived', False), ('waived_at__isnull', True), ('waiver_reason', '')), models.Q(('is_waived', True), ('waived_at__isnull', False), models.Q(('waiver_reason', ''), _negated=True)), _connector='OR'), name='payment_installment_valid_waiver'),
        ),
        migrations.AddConstraint(
            model_name='paymentrecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_record_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='paymentrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'posted'), ('void_reason', ''), ('voided_at__isnull', True)), models.Q(('status', 'voided'), ('voided_at__isnull', False), models.Q(('void_reason', ''), _negated=True)), _connector='OR'), name='payment_record_valid_void_state'),
        ),
        migrations.AddConstraint(
            model_name='paymentrecord',
            constraint=models.CheckConstraint(condition=models.Q(('currency__in', ('RWF', 'USD', 'EUR', 'GBP'))), name='payment_record_valid_currency'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_allocation_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'installment'), name='unique_payment_allocation_pair'),
        ),
    ]
