# Generated by Django 6.0.1 on 2026-09-24 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_payment_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('installment_due', 'Installment Due'), ('milestone_expected', 'Milestone Expected'), ('agreement_expiry', 'Agreement Expiry')], db_index=True, max_length=30)),
                ('timing', models.CharField(choices=[('before', 'Before'), ('on', 'On'), ('after', 'After')], max_length=10)),
                ('days', models.PositiveSmallIntegerField(default=0)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email')], db_index=True, default='in_app', max_length=20)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_rules', to='home.paymentagreement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_reminder_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('agreement_id', 'event', 'timing', 'days', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('installment_due', 'Installment Due'), ('milestone_expected', 'Milestone Expected'), ('agreement_expiry', 'Agreement Expiry')], db_index=True, max_length=30)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('target_date', models.DateField()),
                ('trigger_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_notifications', to='home.paymentagreement')),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_notifications', to='home.paymentinstallment')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_notifications', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='home.paymentreminderrule')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='paymentreminderrule',
            constraint=models.UniqueConstraint(fields=('agreement', 'event', 'timing', 'days', 'channel'), name='unique_payment_reminder_rule'),
        ),
        migrations.AddConstraint(
            model_name='paymentreminderrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('days', 0), ('timing', 'on')), models.Q(('timing__in', ('before', 'after')), ('days__gt', 0)), _connector='OR'), name='payment_reminder_valid_timing'),
        ),
        migrations.AddIndex(
            model_name='paymentnotification',
            index=models.Index(fields=['recipient_user', 'read_at'], name='pay_note_rec_read_idx'),
        ),
    ]
