NEXCODE_ADMIN_GROUP_NAME = "NEXCODE_ADMIN"

NEXCODE_ADMIN_REMEMBER_SESSION_SECONDS = 7 * 24 * 60 * 60

NEXCODE_ADMIN_LOGIN_MAX_FAILURES = 3
NEXCODE_ADMIN_LOGIN_WINDOW_SECONDS = 15 * 60

NEXCODE_ADMIN_PASSWORD_RESET_CODE_SECONDS = 10 * 60

NEXCODE_ADMIN_PASSWORD_RESET_TOKEN_SECONDS = 15 * 60

NEXCODE_ADMIN_PASSWORD_RESET_MAX_ATTEMPTS = 5

NEXCODE_ADMIN_PASSWORD_RESET_REQUEST_COOLDOWN_SECONDS = 60